name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  lint:
    name: Clippy and rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  wasm-build:
    name: WASM Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install wasm-pack
        run: curl -fsSL https://github.com/drager/wasm-pack/releases/download/v0.13.1/wasm-pack-v0.13.1-x86_64-unknown-linux-musl.tar.gz | sudo tar -xz --strip-components=1 -C /usr/local/bin

      - uses: Swatinem/rust-cache@v2
      
      - name: Build with wasm-pack
        run: wasm-pack build --release
      
      - name: Upload pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: pkg/